//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Metamodel.DeepPCM.Core;
using Metamodel.DeepPCM.Core.Entity;
using Metamodel.DeepPCM.Parameter;
using Metamodel.DeepPCM.Reliability;
using Metamodel.DeepPCM.Repository;
using Metamodel.DeepPCM.Seff.Seff_performance;
using Metamodel.DeepPCM.Seff.Seff_reliability;
using Metamodel.Identifier;
using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace Metamodel.DeepPCM.Seff
{
    
    
    /// <summary>
    /// The public interface for EmitEventAction
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(EmitEventAction))]
    [XmlDefaultImplementationTypeAttribute(typeof(EmitEventAction))]
    public interface IEmitEventAction : IModelElement, ICallAction, IAbstractAction
    {
        
        /// <summary>
        /// The eventType__EmitEventAction property
        /// </summary>
        IEventType EventType__EmitEventAction
        {
            get;
            set;
        }
        
        /// <summary>
        /// The eventGroup__EmitEventAction property
        /// </summary>
        Metamodel.DeepPCM.Repository.IEventGroup EventGroup__EmitEventAction
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the EventType__EmitEventAction property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EventType__EmitEventActionChanging;
        
        /// <summary>
        /// Gets fired when the EventType__EmitEventAction property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EventType__EmitEventActionChanged;
        
        /// <summary>
        /// Gets fired before the EventGroup__EmitEventAction property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EventGroup__EmitEventActionChanging;
        
        /// <summary>
        /// Gets fired when the EventGroup__EmitEventAction property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EventGroup__EmitEventActionChanged;
    }
}

