//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using DeepPCM.Deeppcm.Core.Entity;
using DeepPCM.Deeppcm.Parameter;
using DeepPCM.Deeppcm.Repository;
using DeepPCM.Identifier;
using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace DeepPCM.Deeppcm.Core.Composition
{
    
    
    /// <summary>
    /// The default implementation of the RequiredResourceDelegationConnector class
    /// </summary>
    [XmlNamespaceAttribute("http://sdq.ipd.uka.de/PalladioComponentModel/Core/Composition/5.0")]
    [XmlNamespacePrefixAttribute("composition")]
    [ModelRepresentationClassAttribute("http://sdq.ipd.uka.de/PalladioComponentModel/5.0#//core//composition//RequiredRes" +
        "ourceDelegationConnector/")]
    [DebuggerDisplayAttribute("RequiredResourceDelegationConnector {Id}")]
    public class RequiredResourceDelegationConnector : DeepPCM.Deeppcm.Core.Composition.DelegationConnector, IRequiredResourceDelegationConnector, IModelElement
    {
        
        /// <summary>
        /// The backing field for the AssemblyContext__RequiredResourceDelegationConnector property
        /// </summary>
        private IAssemblyContext _assemblyContext__RequiredResourceDelegationConnector;
        
        /// <summary>
        /// The backing field for the InnerRequiredRole__RequiredResourceDelegationConnector property
        /// </summary>
        private IResourceRequiredRole _innerRequiredRole__RequiredResourceDelegationConnector;
        
        /// <summary>
        /// The backing field for the OuterRequiredRole__RequiredResourceDelegationConnector property
        /// </summary>
        private IResourceRequiredRole _outerRequiredRole__RequiredResourceDelegationConnector;
        
        /// <summary>
        /// The assemblyContext__RequiredResourceDelegationConnector property
        /// </summary>
        [XmlElementNameAttribute("assemblyContext__RequiredResourceDelegationConnector")]
        [XmlAttributeAttribute(true)]
        public virtual IAssemblyContext AssemblyContext__RequiredResourceDelegationConnector
        {
            get
            {
                return this._assemblyContext__RequiredResourceDelegationConnector;
            }
            set
            {
                if ((this._assemblyContext__RequiredResourceDelegationConnector != value))
                {
                    IAssemblyContext old = this._assemblyContext__RequiredResourceDelegationConnector;
                    this._assemblyContext__RequiredResourceDelegationConnector = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetAssemblyContext__RequiredResourceDelegationConnector;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetAssemblyContext__RequiredResourceDelegationConnector;
                    }
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnAssemblyContext__RequiredResourceDelegationConnectorChanged(e);
                    this.OnPropertyChanged("AssemblyContext__RequiredResourceDelegationConnector", e);
                }
            }
        }
        
        /// <summary>
        /// The innerRequiredRole__RequiredResourceDelegationConnector property
        /// </summary>
        [XmlElementNameAttribute("innerRequiredRole__RequiredResourceDelegationConnector")]
        [XmlAttributeAttribute(true)]
        public virtual IResourceRequiredRole InnerRequiredRole__RequiredResourceDelegationConnector
        {
            get
            {
                return this._innerRequiredRole__RequiredResourceDelegationConnector;
            }
            set
            {
                if ((this._innerRequiredRole__RequiredResourceDelegationConnector != value))
                {
                    IResourceRequiredRole old = this._innerRequiredRole__RequiredResourceDelegationConnector;
                    this._innerRequiredRole__RequiredResourceDelegationConnector = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetInnerRequiredRole__RequiredResourceDelegationConnector;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetInnerRequiredRole__RequiredResourceDelegationConnector;
                    }
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnInnerRequiredRole__RequiredResourceDelegationConnectorChanged(e);
                    this.OnPropertyChanged("InnerRequiredRole__RequiredResourceDelegationConnector", e);
                }
            }
        }
        
        /// <summary>
        /// The outerRequiredRole__RequiredResourceDelegationConnector property
        /// </summary>
        [XmlElementNameAttribute("outerRequiredRole__RequiredResourceDelegationConnector")]
        [XmlAttributeAttribute(true)]
        public virtual IResourceRequiredRole OuterRequiredRole__RequiredResourceDelegationConnector
        {
            get
            {
                return this._outerRequiredRole__RequiredResourceDelegationConnector;
            }
            set
            {
                if ((this._outerRequiredRole__RequiredResourceDelegationConnector != value))
                {
                    IResourceRequiredRole old = this._outerRequiredRole__RequiredResourceDelegationConnector;
                    this._outerRequiredRole__RequiredResourceDelegationConnector = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetOuterRequiredRole__RequiredResourceDelegationConnector;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetOuterRequiredRole__RequiredResourceDelegationConnector;
                    }
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnOuterRequiredRole__RequiredResourceDelegationConnectorChanged(e);
                    this.OnPropertyChanged("OuterRequiredRole__RequiredResourceDelegationConnector", e);
                }
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new RequiredResourceDelegationConnectorReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class element that describes the structure of this type
        /// </summary>
        public new static NMF.Models.Meta.IClass ClassInstance
        {
            get
            {
                return NMF.Models.Repository.MetaRepository.Instance.ResolveClass("http://sdq.ipd.uka.de/PalladioComponentModel/5.0#//core//composition//RequiredRes" +
                        "ourceDelegationConnector/");
            }
        }
        
        /// <summary>
        /// Gets fired when the AssemblyContext__RequiredResourceDelegationConnector property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> AssemblyContext__RequiredResourceDelegationConnectorChanged;
        
        /// <summary>
        /// Gets fired when the InnerRequiredRole__RequiredResourceDelegationConnector property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> InnerRequiredRole__RequiredResourceDelegationConnectorChanged;
        
        /// <summary>
        /// Gets fired when the OuterRequiredRole__RequiredResourceDelegationConnector property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> OuterRequiredRole__RequiredResourceDelegationConnectorChanged;
        
        /// <summary>
        /// Raises the AssemblyContext__RequiredResourceDelegationConnectorChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnAssemblyContext__RequiredResourceDelegationConnectorChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.AssemblyContext__RequiredResourceDelegationConnectorChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the AssemblyContext__RequiredResourceDelegationConnector property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetAssemblyContext__RequiredResourceDelegationConnector(object sender, EventArgs eventArgs)
        {
            this.AssemblyContext__RequiredResourceDelegationConnector = null;
        }
        
        /// <summary>
        /// Raises the InnerRequiredRole__RequiredResourceDelegationConnectorChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnInnerRequiredRole__RequiredResourceDelegationConnectorChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.InnerRequiredRole__RequiredResourceDelegationConnectorChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the InnerRequiredRole__RequiredResourceDelegationConnector property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetInnerRequiredRole__RequiredResourceDelegationConnector(object sender, EventArgs eventArgs)
        {
            this.InnerRequiredRole__RequiredResourceDelegationConnector = null;
        }
        
        /// <summary>
        /// Raises the OuterRequiredRole__RequiredResourceDelegationConnectorChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnOuterRequiredRole__RequiredResourceDelegationConnectorChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.OuterRequiredRole__RequiredResourceDelegationConnectorChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the OuterRequiredRole__RequiredResourceDelegationConnector property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetOuterRequiredRole__RequiredResourceDelegationConnector(object sender, EventArgs eventArgs)
        {
            this.OuterRequiredRole__RequiredResourceDelegationConnector = null;
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "ASSEMBLYCONTEXT__REQUIREDRESOURCEDELEGATIONCONNECTOR"))
            {
                this.AssemblyContext__RequiredResourceDelegationConnector = ((IAssemblyContext)(value));
                return;
            }
            if ((feature == "INNERREQUIREDROLE__REQUIREDRESOURCEDELEGATIONCONNECTOR"))
            {
                this.InnerRequiredRole__RequiredResourceDelegationConnector = ((IResourceRequiredRole)(value));
                return;
            }
            if ((feature == "OUTERREQUIREDROLE__REQUIREDRESOURCEDELEGATIONCONNECTOR"))
            {
                this.OuterRequiredRole__RequiredResourceDelegationConnector = ((IResourceRequiredRole)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "ASSEMBLYCONTEXT__REQUIREDRESOURCEDELEGATIONCONNECTOR"))
            {
                return new AssemblyContext__RequiredResourceDelegationConnectorProxy(this);
            }
            if ((attribute == "INNERREQUIREDROLE__REQUIREDRESOURCEDELEGATIONCONNECTOR"))
            {
                return new InnerRequiredRole__RequiredResourceDelegationConnectorProxy(this);
            }
            if ((attribute == "OUTERREQUIREDROLE__REQUIREDRESOURCEDELEGATIONCONNECTOR"))
            {
                return new OuterRequiredRole__RequiredResourceDelegationConnectorProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "ASSEMBLYCONTEXT__REQUIREDRESOURCEDELEGATIONCONNECTOR"))
            {
                return new AssemblyContext__RequiredResourceDelegationConnectorProxy(this);
            }
            if ((reference == "INNERREQUIREDROLE__REQUIREDRESOURCEDELEGATIONCONNECTOR"))
            {
                return new InnerRequiredRole__RequiredResourceDelegationConnectorProxy(this);
            }
            if ((reference == "OUTERREQUIREDROLE__REQUIREDRESOURCEDELEGATIONCONNECTOR"))
            {
                return new OuterRequiredRole__RequiredResourceDelegationConnectorProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the Delegate for this model element
        /// </summary>
        public override IDelegate GetDelegate()
        {
            return ((IDelegate)(NMF.Models.Repository.MetaRepository.Instance.Resolve("http://sdq.ipd.uka.de/PalladioComponentModel/5.0#//core//composition//RequiredRes" +
                    "ourceDelegationConnector/")));
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            return ((IClass)(NMF.Models.Repository.MetaRepository.Instance.Resolve("http://sdq.ipd.uka.de/PalladioComponentModel/5.0#//core//composition//RequiredRes" +
                    "ourceDelegationConnector/")));
        }
        
        /// <summary>
        /// The collection class to to represent the children of the RequiredResourceDelegationConnector class
        /// </summary>
        public class RequiredResourceDelegationConnectorReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private RequiredResourceDelegationConnector _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public RequiredResourceDelegationConnectorReferencedElementsCollection(RequiredResourceDelegationConnector parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.AssemblyContext__RequiredResourceDelegationConnector != null))
                    {
                        count = (count + 1);
                    }
                    if ((this._parent.InnerRequiredRole__RequiredResourceDelegationConnector != null))
                    {
                        count = (count + 1);
                    }
                    if ((this._parent.OuterRequiredRole__RequiredResourceDelegationConnector != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.AssemblyContext__RequiredResourceDelegationConnectorChanged += this.PropagateValueChanges;
                this._parent.InnerRequiredRole__RequiredResourceDelegationConnectorChanged += this.PropagateValueChanges;
                this._parent.OuterRequiredRole__RequiredResourceDelegationConnectorChanged += this.PropagateValueChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.AssemblyContext__RequiredResourceDelegationConnectorChanged -= this.PropagateValueChanges;
                this._parent.InnerRequiredRole__RequiredResourceDelegationConnectorChanged -= this.PropagateValueChanges;
                this._parent.OuterRequiredRole__RequiredResourceDelegationConnectorChanged -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.AssemblyContext__RequiredResourceDelegationConnector == null))
                {
                    IAssemblyContext assemblyContext__RequiredResourceDelegationConnectorCasted = item.As<IAssemblyContext>();
                    if ((assemblyContext__RequiredResourceDelegationConnectorCasted != null))
                    {
                        this._parent.AssemblyContext__RequiredResourceDelegationConnector = assemblyContext__RequiredResourceDelegationConnectorCasted;
                        return;
                    }
                }
                if ((this._parent.InnerRequiredRole__RequiredResourceDelegationConnector == null))
                {
                    IResourceRequiredRole innerRequiredRole__RequiredResourceDelegationConnectorCasted = item.As<IResourceRequiredRole>();
                    if ((innerRequiredRole__RequiredResourceDelegationConnectorCasted != null))
                    {
                        this._parent.InnerRequiredRole__RequiredResourceDelegationConnector = innerRequiredRole__RequiredResourceDelegationConnectorCasted;
                        return;
                    }
                }
                if ((this._parent.OuterRequiredRole__RequiredResourceDelegationConnector == null))
                {
                    IResourceRequiredRole outerRequiredRole__RequiredResourceDelegationConnectorCasted = item.As<IResourceRequiredRole>();
                    if ((outerRequiredRole__RequiredResourceDelegationConnectorCasted != null))
                    {
                        this._parent.OuterRequiredRole__RequiredResourceDelegationConnector = outerRequiredRole__RequiredResourceDelegationConnectorCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.AssemblyContext__RequiredResourceDelegationConnector = null;
                this._parent.InnerRequiredRole__RequiredResourceDelegationConnector = null;
                this._parent.OuterRequiredRole__RequiredResourceDelegationConnector = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.AssemblyContext__RequiredResourceDelegationConnector))
                {
                    return true;
                }
                if ((item == this._parent.InnerRequiredRole__RequiredResourceDelegationConnector))
                {
                    return true;
                }
                if ((item == this._parent.OuterRequiredRole__RequiredResourceDelegationConnector))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.AssemblyContext__RequiredResourceDelegationConnector != null))
                {
                    array[arrayIndex] = this._parent.AssemblyContext__RequiredResourceDelegationConnector;
                    arrayIndex = (arrayIndex + 1);
                }
                if ((this._parent.InnerRequiredRole__RequiredResourceDelegationConnector != null))
                {
                    array[arrayIndex] = this._parent.InnerRequiredRole__RequiredResourceDelegationConnector;
                    arrayIndex = (arrayIndex + 1);
                }
                if ((this._parent.OuterRequiredRole__RequiredResourceDelegationConnector != null))
                {
                    array[arrayIndex] = this._parent.OuterRequiredRole__RequiredResourceDelegationConnector;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.AssemblyContext__RequiredResourceDelegationConnector == item))
                {
                    this._parent.AssemblyContext__RequiredResourceDelegationConnector = null;
                    return true;
                }
                if ((this._parent.InnerRequiredRole__RequiredResourceDelegationConnector == item))
                {
                    this._parent.InnerRequiredRole__RequiredResourceDelegationConnector = null;
                    return true;
                }
                if ((this._parent.OuterRequiredRole__RequiredResourceDelegationConnector == item))
                {
                    this._parent.OuterRequiredRole__RequiredResourceDelegationConnector = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.AssemblyContext__RequiredResourceDelegationConnector).Concat(this._parent.InnerRequiredRole__RequiredResourceDelegationConnector).Concat(this._parent.OuterRequiredRole__RequiredResourceDelegationConnector).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the assemblyContext__RequiredResourceDelegationConnector property
        /// </summary>
        private sealed class AssemblyContext__RequiredResourceDelegationConnectorProxy : ModelPropertyChange<IRequiredResourceDelegationConnector, IAssemblyContext>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public AssemblyContext__RequiredResourceDelegationConnectorProxy(IRequiredResourceDelegationConnector modelElement) : 
                    base(modelElement)
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IAssemblyContext Value
            {
                get
                {
                    return this.ModelElement.AssemblyContext__RequiredResourceDelegationConnector;
                }
                set
                {
                    this.ModelElement.AssemblyContext__RequiredResourceDelegationConnector = value;
                }
            }
            
            /// <summary>
            /// Registers an event handler to subscribe specifically on the changed event for this property
            /// </summary>
            /// <param name="handler">The handler that should be subscribed to the property change event</param>
            protected override void RegisterChangeEventHandler(System.EventHandler<NMF.Expressions.ValueChangedEventArgs> handler)
            {
                this.ModelElement.AssemblyContext__RequiredResourceDelegationConnectorChanged += handler;
            }
            
            /// <summary>
            /// Registers an event handler to subscribe specifically on the changed event for this property
            /// </summary>
            /// <param name="handler">The handler that should be unsubscribed from the property change event</param>
            protected override void UnregisterChangeEventHandler(System.EventHandler<NMF.Expressions.ValueChangedEventArgs> handler)
            {
                this.ModelElement.AssemblyContext__RequiredResourceDelegationConnectorChanged -= handler;
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the innerRequiredRole__RequiredResourceDelegationConnector property
        /// </summary>
        private sealed class InnerRequiredRole__RequiredResourceDelegationConnectorProxy : ModelPropertyChange<IRequiredResourceDelegationConnector, IResourceRequiredRole>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public InnerRequiredRole__RequiredResourceDelegationConnectorProxy(IRequiredResourceDelegationConnector modelElement) : 
                    base(modelElement)
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IResourceRequiredRole Value
            {
                get
                {
                    return this.ModelElement.InnerRequiredRole__RequiredResourceDelegationConnector;
                }
                set
                {
                    this.ModelElement.InnerRequiredRole__RequiredResourceDelegationConnector = value;
                }
            }
            
            /// <summary>
            /// Registers an event handler to subscribe specifically on the changed event for this property
            /// </summary>
            /// <param name="handler">The handler that should be subscribed to the property change event</param>
            protected override void RegisterChangeEventHandler(System.EventHandler<NMF.Expressions.ValueChangedEventArgs> handler)
            {
                this.ModelElement.InnerRequiredRole__RequiredResourceDelegationConnectorChanged += handler;
            }
            
            /// <summary>
            /// Registers an event handler to subscribe specifically on the changed event for this property
            /// </summary>
            /// <param name="handler">The handler that should be unsubscribed from the property change event</param>
            protected override void UnregisterChangeEventHandler(System.EventHandler<NMF.Expressions.ValueChangedEventArgs> handler)
            {
                this.ModelElement.InnerRequiredRole__RequiredResourceDelegationConnectorChanged -= handler;
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the outerRequiredRole__RequiredResourceDelegationConnector property
        /// </summary>
        private sealed class OuterRequiredRole__RequiredResourceDelegationConnectorProxy : ModelPropertyChange<IRequiredResourceDelegationConnector, IResourceRequiredRole>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public OuterRequiredRole__RequiredResourceDelegationConnectorProxy(IRequiredResourceDelegationConnector modelElement) : 
                    base(modelElement)
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IResourceRequiredRole Value
            {
                get
                {
                    return this.ModelElement.OuterRequiredRole__RequiredResourceDelegationConnector;
                }
                set
                {
                    this.ModelElement.OuterRequiredRole__RequiredResourceDelegationConnector = value;
                }
            }
            
            /// <summary>
            /// Registers an event handler to subscribe specifically on the changed event for this property
            /// </summary>
            /// <param name="handler">The handler that should be subscribed to the property change event</param>
            protected override void RegisterChangeEventHandler(System.EventHandler<NMF.Expressions.ValueChangedEventArgs> handler)
            {
                this.ModelElement.OuterRequiredRole__RequiredResourceDelegationConnectorChanged += handler;
            }
            
            /// <summary>
            /// Registers an event handler to subscribe specifically on the changed event for this property
            /// </summary>
            /// <param name="handler">The handler that should be unsubscribed from the property change event</param>
            protected override void UnregisterChangeEventHandler(System.EventHandler<NMF.Expressions.ValueChangedEventArgs> handler)
            {
                this.ModelElement.OuterRequiredRole__RequiredResourceDelegationConnectorChanged -= handler;
            }
        }
    }
}

