//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using GeneratedCode.Pcm.Core;
using GeneratedCode.Pcm.Core.Entity;
using GeneratedCode.Pcm.Parameter;
using GeneratedCode.Pcm.Protocol;
using GeneratedCode.Pcm.Reliability;
using GeneratedCode.Pcm.Resourcetype;
using GeneratedCode.Pcm.Seff;
using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace GeneratedCode.Pcm.Repository
{
    
    
    /// <summary>
    /// The default implementation of the Interface class
    /// </summary>
    [XmlNamespaceAttribute("http://sdq.ipd.uka.de/PalladioComponentModel/Repository/5.0")]
    [XmlNamespacePrefixAttribute("repository")]
    [ModelRepresentationClassAttribute("http://sdq.ipd.uka.de/PalladioComponentModel/5.0#//repository//Interface/")]
    [DebuggerDisplayAttribute("Interface {Id}")]
    public abstract class Interface : GeneratedCode.Pcm.Core.Entity.Entity, IInterface, IModelElement
    {
        
        /// <summary>
        /// The backing field for the ParentInterfaces__Interface property
        /// </summary>
        private ObservableAssociationList<IInterface> _parentInterfaces__Interface;
        
        /// <summary>
        /// The backing field for the Protocols__Interface property
        /// </summary>
        private ObservableCompositionList<IProtocol> _protocols__Interface;
        
        /// <summary>
        /// The backing field for the RequiredCharacterisations property
        /// </summary>
        private InterfaceRequiredCharacterisationsCollection _requiredCharacterisations;
        
        public Interface()
        {
            this._parentInterfaces__Interface = new ObservableAssociationList<IInterface>();
            this._parentInterfaces__Interface.CollectionChanged += this.ParentInterfaces__InterfaceCollectionChanged;
            this._protocols__Interface = new ObservableCompositionList<IProtocol>(this);
            this._protocols__Interface.CollectionChanged += this.Protocols__InterfaceCollectionChanged;
            this._requiredCharacterisations = new InterfaceRequiredCharacterisationsCollection(this);
            this._requiredCharacterisations.CollectionChanged += this.RequiredCharacterisationsCollectionChanged;
        }
        
        /// <summary>
        /// The parentInterfaces__Interface property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlElementNameAttribute("parentInterfaces__Interface")]
        [XmlAttributeAttribute(true)]
        [ConstantAttribute()]
        public virtual ICollectionExpression<IInterface> ParentInterfaces__Interface
        {
            get
            {
                return this._parentInterfaces__Interface;
            }
        }
        
        /// <summary>
        /// The protocols__Interface property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlElementNameAttribute("protocols__Interface")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        public virtual ICollectionExpression<IProtocol> Protocols__Interface
        {
            get
            {
                return this._protocols__Interface;
            }
        }
        
        /// <summary>
        /// The requiredCharacterisations property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlElementNameAttribute("requiredCharacterisations")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("interface_RequiredCharacterisation")]
        [ConstantAttribute()]
        public virtual ICollectionExpression<IRequiredCharacterisation> RequiredCharacterisations
        {
            get
            {
                return this._requiredCharacterisations;
            }
        }
        
        /// <summary>
        /// The repository__Interface property
        /// </summary>
        [XmlElementNameAttribute("repository__Interface")]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("interfaces__Repository")]
        public virtual IRepository Repository__Interface
        {
            get
            {
                return ModelHelper.CastAs<IRepository>(this.Parent);
            }
            set
            {
                this.Parent = value;
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new InterfaceChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new InterfaceReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class element that describes the structure of this type
        /// </summary>
        public new static NMF.Models.Meta.IClass ClassInstance
        {
            get
            {
                return NMF.Models.Repository.MetaRepository.Instance.ResolveClass("http://sdq.ipd.uka.de/PalladioComponentModel/5.0#//repository//Interface/");
            }
        }
        
        /// <summary>
        /// Gets fired when the Repository__Interface property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> Repository__InterfaceChanged;
        
        /// <summary>
        /// Forwards change notifications for the ParentInterfaces__Interface property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ParentInterfaces__InterfaceCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("ParentInterfaces__Interface", e);
        }
        
        /// <summary>
        /// Forwards change notifications for the Protocols__Interface property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void Protocols__InterfaceCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Protocols__Interface", e);
        }
        
        /// <summary>
        /// Forwards change notifications for the RequiredCharacterisations property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void RequiredCharacterisationsCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("RequiredCharacterisations", e);
        }
        
        /// <summary>
        /// Raises the Repository__InterfaceChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnRepository__InterfaceChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.Repository__InterfaceChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Gets called when the parent model element of the current model element changes
        /// </summary>
        /// <param name="oldParent">The old parent model element</param>
        /// <param name="newParent">The new parent model element</param>
        protected override void OnParentChanged(IModelElement newParent, IModelElement oldParent)
        {
            IRepository oldRepository__Interface = ModelHelper.CastAs<IRepository>(oldParent);
            IRepository newRepository__Interface = ModelHelper.CastAs<IRepository>(newParent);
            if ((oldRepository__Interface != null))
            {
                oldRepository__Interface.Interfaces__Repository.Remove(this);
            }
            if ((newRepository__Interface != null))
            {
                newRepository__Interface.Interfaces__Repository.Add(this);
            }
            ValueChangedEventArgs e = new ValueChangedEventArgs(oldRepository__Interface, newRepository__Interface);
            this.OnRepository__InterfaceChanged(e);
            this.OnPropertyChanged("Repository__Interface", e);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "PARENTINTERFACES__INTERFACE"))
            {
                return this._parentInterfaces__Interface;
            }
            if ((feature == "PROTOCOLS__INTERFACE"))
            {
                return this._protocols__Interface;
            }
            if ((feature == "REQUIREDCHARACTERISATIONS"))
            {
                return this._requiredCharacterisations;
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "REPOSITORY__INTERFACE"))
            {
                this.Repository__Interface = ((IRepository)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "REPOSITORY__INTERFACE"))
            {
                return new Repository__InterfaceProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "REPOSITORY__INTERFACE"))
            {
                return new Repository__InterfaceProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            return ((IClass)(NMF.Models.Repository.MetaRepository.Instance.Resolve("http://sdq.ipd.uka.de/PalladioComponentModel/5.0#//repository//Interface/")));
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Interface class
        /// </summary>
        public class InterfaceChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Interface _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public InterfaceChildrenCollection(Interface parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Protocols__Interface.Count);
                    count = (count + this._parent.RequiredCharacterisations.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.Protocols__Interface.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.RequiredCharacterisations.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.Protocols__Interface.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.RequiredCharacterisations.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                IProtocol protocols__InterfaceCasted = item.As<IProtocol>();
                if ((protocols__InterfaceCasted != null))
                {
                    this._parent.Protocols__Interface.Add(protocols__InterfaceCasted);
                }
                IRequiredCharacterisation requiredCharacterisationsCasted = item.As<IRequiredCharacterisation>();
                if ((requiredCharacterisationsCasted != null))
                {
                    this._parent.RequiredCharacterisations.Add(requiredCharacterisationsCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Protocols__Interface.Clear();
                this._parent.RequiredCharacterisations.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Protocols__Interface.Contains(item))
                {
                    return true;
                }
                if (this._parent.RequiredCharacterisations.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> protocols__InterfaceEnumerator = this._parent.Protocols__Interface.GetEnumerator();
                try
                {
                    for (
                    ; protocols__InterfaceEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = protocols__InterfaceEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    protocols__InterfaceEnumerator.Dispose();
                }
                IEnumerator<IModelElement> requiredCharacterisationsEnumerator = this._parent.RequiredCharacterisations.GetEnumerator();
                try
                {
                    for (
                    ; requiredCharacterisationsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = requiredCharacterisationsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    requiredCharacterisationsEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                IProtocol protocolItem = item.As<IProtocol>();
                if (((protocolItem != null) 
                            && this._parent.Protocols__Interface.Remove(protocolItem)))
                {
                    return true;
                }
                IRequiredCharacterisation requiredCharacterisationItem = item.As<IRequiredCharacterisation>();
                if (((requiredCharacterisationItem != null) 
                            && this._parent.RequiredCharacterisations.Remove(requiredCharacterisationItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Protocols__Interface).Concat(this._parent.RequiredCharacterisations).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Interface class
        /// </summary>
        public class InterfaceReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Interface _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public InterfaceReferencedElementsCollection(Interface parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.ParentInterfaces__Interface.Count);
                    count = (count + this._parent.Protocols__Interface.Count);
                    count = (count + this._parent.RequiredCharacterisations.Count);
                    if ((this._parent.Repository__Interface != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.ParentInterfaces__Interface.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.Protocols__Interface.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.RequiredCharacterisations.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.Repository__InterfaceChanged += this.PropagateValueChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.ParentInterfaces__Interface.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.Protocols__Interface.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.RequiredCharacterisations.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.Repository__InterfaceChanged -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                IInterface parentInterfaces__InterfaceCasted = item.As<IInterface>();
                if ((parentInterfaces__InterfaceCasted != null))
                {
                    this._parent.ParentInterfaces__Interface.Add(parentInterfaces__InterfaceCasted);
                }
                IProtocol protocols__InterfaceCasted = item.As<IProtocol>();
                if ((protocols__InterfaceCasted != null))
                {
                    this._parent.Protocols__Interface.Add(protocols__InterfaceCasted);
                }
                IRequiredCharacterisation requiredCharacterisationsCasted = item.As<IRequiredCharacterisation>();
                if ((requiredCharacterisationsCasted != null))
                {
                    this._parent.RequiredCharacterisations.Add(requiredCharacterisationsCasted);
                }
                if ((this._parent.Repository__Interface == null))
                {
                    IRepository repository__InterfaceCasted = item.As<IRepository>();
                    if ((repository__InterfaceCasted != null))
                    {
                        this._parent.Repository__Interface = repository__InterfaceCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.ParentInterfaces__Interface.Clear();
                this._parent.Protocols__Interface.Clear();
                this._parent.RequiredCharacterisations.Clear();
                this._parent.Repository__Interface = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.ParentInterfaces__Interface.Contains(item))
                {
                    return true;
                }
                if (this._parent.Protocols__Interface.Contains(item))
                {
                    return true;
                }
                if (this._parent.RequiredCharacterisations.Contains(item))
                {
                    return true;
                }
                if ((item == this._parent.Repository__Interface))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> parentInterfaces__InterfaceEnumerator = this._parent.ParentInterfaces__Interface.GetEnumerator();
                try
                {
                    for (
                    ; parentInterfaces__InterfaceEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = parentInterfaces__InterfaceEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    parentInterfaces__InterfaceEnumerator.Dispose();
                }
                IEnumerator<IModelElement> protocols__InterfaceEnumerator = this._parent.Protocols__Interface.GetEnumerator();
                try
                {
                    for (
                    ; protocols__InterfaceEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = protocols__InterfaceEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    protocols__InterfaceEnumerator.Dispose();
                }
                IEnumerator<IModelElement> requiredCharacterisationsEnumerator = this._parent.RequiredCharacterisations.GetEnumerator();
                try
                {
                    for (
                    ; requiredCharacterisationsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = requiredCharacterisationsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    requiredCharacterisationsEnumerator.Dispose();
                }
                if ((this._parent.Repository__Interface != null))
                {
                    array[arrayIndex] = this._parent.Repository__Interface;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                IInterface interfaceItem = item.As<IInterface>();
                if (((interfaceItem != null) 
                            && this._parent.ParentInterfaces__Interface.Remove(interfaceItem)))
                {
                    return true;
                }
                IProtocol protocolItem = item.As<IProtocol>();
                if (((protocolItem != null) 
                            && this._parent.Protocols__Interface.Remove(protocolItem)))
                {
                    return true;
                }
                IRequiredCharacterisation requiredCharacterisationItem = item.As<IRequiredCharacterisation>();
                if (((requiredCharacterisationItem != null) 
                            && this._parent.RequiredCharacterisations.Remove(requiredCharacterisationItem)))
                {
                    return true;
                }
                if ((this._parent.Repository__Interface == item))
                {
                    this._parent.Repository__Interface = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.ParentInterfaces__Interface).Concat(this._parent.Protocols__Interface).Concat(this._parent.RequiredCharacterisations).Concat(this._parent.Repository__Interface).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the repository__Interface property
        /// </summary>
        private sealed class Repository__InterfaceProxy : ModelPropertyChange<IInterface, IRepository>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public Repository__InterfaceProxy(IInterface modelElement) : 
                    base(modelElement)
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IRepository Value
            {
                get
                {
                    return this.ModelElement.Repository__Interface;
                }
                set
                {
                    this.ModelElement.Repository__Interface = value;
                }
            }
            
            /// <summary>
            /// Registers an event handler to subscribe specifically on the changed event for this property
            /// </summary>
            /// <param name="handler">The handler that should be subscribed to the property change event</param>
            protected override void RegisterChangeEventHandler(System.EventHandler<NMF.Expressions.ValueChangedEventArgs> handler)
            {
                this.ModelElement.Repository__InterfaceChanged += handler;
            }
            
            /// <summary>
            /// Registers an event handler to subscribe specifically on the changed event for this property
            /// </summary>
            /// <param name="handler">The handler that should be unsubscribed from the property change event</param>
            protected override void UnregisterChangeEventHandler(System.EventHandler<NMF.Expressions.ValueChangedEventArgs> handler)
            {
                this.ModelElement.Repository__InterfaceChanged -= handler;
            }
        }
    }
}

