//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using GeneratedCode.Pcm.Core;
using GeneratedCode.Pcm.Core.Entity;
using GeneratedCode.Pcm.Parameter;
using GeneratedCode.Pcm.Repository;
using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace GeneratedCode.Pcm.Core.Composition
{
    
    
    /// <summary>
    /// The public interface for EventChannelSourceConnector
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(EventChannelSourceConnector))]
    [XmlDefaultImplementationTypeAttribute(typeof(EventChannelSourceConnector))]
    public interface IEventChannelSourceConnector : IModelElement, IConnector
    {
        
        /// <summary>
        /// The sourceRole__EventChannelSourceRole property
        /// </summary>
        ISourceRole SourceRole__EventChannelSourceRole
        {
            get;
            set;
        }
        
        /// <summary>
        /// The assemblyContext__EventChannelSourceConnector property
        /// </summary>
        IAssemblyContext AssemblyContext__EventChannelSourceConnector
        {
            get;
            set;
        }
        
        /// <summary>
        /// The eventChannel__EventChannelSourceConnector property
        /// </summary>
        IEventChannel EventChannel__EventChannelSourceConnector
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired when the SourceRole__EventChannelSourceRole property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> SourceRole__EventChannelSourceRoleChanged;
        
        /// <summary>
        /// Gets fired when the AssemblyContext__EventChannelSourceConnector property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> AssemblyContext__EventChannelSourceConnectorChanged;
        
        /// <summary>
        /// Gets fired when the EventChannel__EventChannelSourceConnector property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> EventChannel__EventChannelSourceConnectorChanged;
    }
}

